config/routes.rb
Awesomewallet::Application.routes.draw do
	root to: 'dashboard#index'

	resources :transactions
	match "/auth/:provider/callback" => "sessions#create"
end

app/models/identity.rb
class Identity
  include Mongoid::Document
  field :provider, type: String
  field :uid, type: String
  field :user_id, type: Integer
  belongs_to :user

  def self.find_with_omniauth(auth)
    where(provider: auth['provider'], uid: auth['uid']).first
  end

  def self.create_with_omniauth(auth)
    create(uid: auth['uid'], provider: auth['provider'])
  end
end

app/models/transaction.rb
class Transaction
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::MultiParameterAttributes

  before_create :set_user_balance
  before_create :set_current_balance

  field :user_id, type: Integer
  field :name, type: String
  field :amount, type: BigDecimal
  field :kind, type: Symbol
  field :current_balance, type: BigDecimal

  validates :amount, numericality: true
  validates :name, :kind, :amount, presence: true
  validates :kind, inclusion: { in: %i(income outcome) }

  belongs_to :user

  default_scope desc(:created_at)
  
  scope :by_date_range, ->(from, to) { where(:created_at.gte => from).where(:created_at.lte => to) }

  private  
  def set_current_balance
    self.current_balance = user.balance
  end

  def set_user_balance
    kind == :income ? user.balance += amount : user.balance -= amount
    user.save
  end
end

app/models/user.rb
class User
  include Mongoid::Document

  field :name, type: String
  field :email, type: String
  field :balance, type: BigDecimal, default: 0
  index({ email: 1 }, { unique: true, background: true })

  has_many :identities
  has_many :transactions

  validates_presence_of :name

  attr_accessible :name, :email

  def self.create_with_omniauth(auth)
    user = User.where(email: auth['info']['email']).first
    return user if user.present?
    create! do |user|
      if auth['info']
         user.name = auth['info']['name'] || ""
         user.email = auth['info']['email'] || ""
      end
    end
  end

  def total_amount(kind)
    transactions.where(kind: kind).map(&:amount).sum.to_f
  end

  def transactions_per_day(from, to)
    searched = transactions.by_date_range(from, to)
    searched.group_by{ |transaction| transaction.created_at.to_date }.collect{ |group| {date: group[0] , number_of_transactions: group[1].count} }
  end

  def balance_history(start_date, end_date)
    data = transactions.by_date_range(start_date, end_date).
      group_by{ |t| t.created_at.to_date }.map { |k, v| { data: k, balance: v.first.current_balance } }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user
  helper_method :user_signed_in?
  helper_method :correct_user?

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id].present?
  end

  def signed_in?
    !!current_user
  end
  helper_method :current_user, :signed_in?

  def current_user=(user)
    @current_user = user
    session[:user_id] = user.nil? ? user : user.id
  end

  def authenticate_user!
    if !current_user
      redirect_to root_url, alert: 'You need to sign in for access to this page.'
    end
  end

  def self.authenticate_user!
    before_filter :authenticate_user!
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    redirect_to '/auth/google_oauth2'
  end


  def create
    auth = request.env['omniauth.auth']
    @identity = Identity.find_with_omniauth(auth)
    if @identity.nil?
      @identity = Identity.create_with_omniauth(auth)
    end
    if signed_in?
      if @identity.user == current_user
        redirect_to transactions_path, notice: "Already linked that account!"
      else
        @identity.user = current_user
        @identity.save
        redirect_to transactions_path, notice: "Successfully linked that account!"
      end
    else
      if @identity.user.present?
        self.current_user = @identity.user
        redirect_to transactions_path, notice: "Signed in!"
      else
        self.current_user = User.create_with_omniauth(auth)
        redirect_to transactions_path
      end
    end
  end

  def destroy
    self.current_user = nil
    redirect_to root_url, notice: "Signed out!"
  end

  def failure
    redirect_to root_url, alert: "Authentication error: #{params[:message].humanize}"
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  authenticate_user!

  expose(:transactions) { searched_transactions.page(params[:page]) }
  expose(:transaction)

  def index
    @per_day_data = if params[:date] && params[:date][:from] && params[:date][:to]
                   current_user.transactions_per_day(Date.parse(params[:date][:from]), Date.parse(params[:date][:to]))
                 end
    @balance_history_data = if params[:date] && params[:date][:from] && params[:date][:to]
                   current_user.balance_history(Date.parse(params[:date][:from]), Date.parse(params[:date][:to]))
                 end
  end

  def create
    if transaction.save
      redirect_to transactions_path, notice: "Transaction created!"
    else
      render :new
    end
  end

  def update
    if transaction.save
      redirect_to transactions_path, notice: "Transaction updated!"
    else
      render :edit
    end
  end

  def destroy
    transaction.destroy
    redirect_to transactions_path, notice: "Transaction destroyed!"
  end

  def chart_counts

  end

  def chart_balance

  end

  def get_transactions
  end

  private
  def searched_transactions
    search = current_user.transactions
    if params[:date]
      search = search.where(:created_at.gte => Date.parse(params[:date][:from]).beginning_of_day) if params[:date][:from].present?
      search = search.where(:created_at.lte => Date.parse(params[:date][:to]).end_of_day) if params[:date][:to].present?
    end
    search
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def auth_for(provider)
    "/auth/#{provider}"
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
  def signed_amount(transaction)
    "#{transaction.kind == :outcome ? '-' : '+'}#{transaction.amount}"
  end

  def kind_label(transaction)
    case transaction.kind
    when :income then "success"
    when :outcome then "error"
    end
  end
end

app/helpers/user_helper.rb
module UserHelper
  def balance_label(balance)
    balance > 0 ? "success" : "important"
  end
end

app/views/dashboard/index.html.haml
%chart{path: 'lol', type: 'pie'}

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{class: "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, id: "flash_#{name}"

app/views/layouts/_navigation.html.haml
= link_to "AwesomeWallet", transactions_path, class: 'brand'
%ul.nav.pull-right
  - if signed_in?
    %li
      %a{ href: "#" } Logged in as #{current_user.name}
    %li
      %a{ href: "#" }
        Balance:
        %span{class: "label label-#{balance_label(current_user.balance)}"}= current_user.balance
    %li
      = link_to 'Logout', logout_path
  - else
    %a.btn.dropdown-toggle{data: {toggle: 'dropdown'}, href: '#'}
      Login
      %span.caret
    %ul.dropdown-menu
      %li
        = link_to 'Github', auth_for("github")
        = link_to 'Google', auth_for("google_oauth2")
        = link_to 'Facebook', auth_for("facebook")

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}
      %title= content_for?(:title) ? yield(:title) : "AwesomeWallet"
      %meta{content: content_for?(:description) ? yield(:description) : "Awesomewallet", name: "description"}
        = stylesheet_link_tag "application", media: "all"
        = csrf_meta_tags
        = yield(:head)
  %body{class: "#{controller_name} #{action_name}"}
    .navbar.navbar-fixed-top
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main{role: "main"}
      .container
        .content
          .row
            .span12
              = render 'layouts/messages'
              = yield
          %footer
      / ! end of .container
    / ! end of #main
    = javascript_include_tag "application"

app/views/transactions/index.html.haml
%h1
  Transactions
  = link_to "Add transaction", new_transaction_path, class: "btn"

%span.label.label-success Total income: #{current_user.total_amount(:income)}
%span.label.label-important Total outcome: #{current_user.total_amount(:outcome)}

.pull-right
  = simple_form_for :date, url: transactions_path, method: 'get', html: { class: "form-inline" } do |f|
    = f.text_field :from, class: 'datepicker', placeholder: "from"
    = f.text_field :to, class: 'datepicker', placeholder: "to"
    = f.submit "Search"

%table.table.table-bordered
  %tr
    %th Kind
    %th Name
    %th Amount
    %th Created at

  - transactions.each do |transaction|
    %tr{class: kind_label(transaction)}
      %td= transaction.kind
      %td= transaction.name
      %td= signed_amount(transaction)
      %td= transaction.created_at.strftime("%d %b %Y %H:%M")

= paginate transactions

-if @per_day_data
  %h2 Transactions per day
  %chart{data: @per_day_data.to_json,
          xkey: 'date',
          ykeys: 'number_of_transactions',
          labels: 'test',
          type: 'bar'}
-if @balance_history_data
  %h2 Balance history
  %chart{data: @balance_history_data.to_json,
          xkey: 'data',
          ykeys: 'balance',
          labels: 'test',
          type: 'line'}

app/views/transactions/new.html.haml
= simple_form_for transaction do |f|
  = f.input :name
  = f.input :kind, collection: ["income", "outcome"]
  = f.input :amount
  = f.button :submit